Application\Entity\PostEntity:
    properties:
        title:
            - NotBlank:
                groups: [ newAndEdit ]

Application\Entity\ProfileEntity:
    properties:
        image:
            - Image:
                groups: [ newAndEdit ]

Application\Entity\UserEntity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            message: 'This email is already in use'
            groups: [ new, edit, register, settings ]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            message: 'This username is already in use'
            groups: [ new, edit, register, settings ]
    properties:
        username:
            - NotBlank:
                groups: [ new, edit, register, settings ]
        email:
            - NotBlank:
                groups: [ new, edit, register, settings, resetPasswordRequest ]
            - Email:
                groups: [ new, edit, register, settings, resetPasswordRequest ]
        plainPassword:
            - NotBlank:
                groups: [ new, register, settingsPassword, resetPasswordReset ]
        oldPassword:
            - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
                groups: [ settingsPassword ]
        profile:
            - Valid: ~

Application\Entity\CountryEntity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: slug
            message: 'This slug is already in use'
            groups: [ newAndEdit ]
    properties:
        name:
            - NotBlank:
                groups: [ newAndEdit ]
        slug:
            - NotBlank:
                groups: [ newAndEdit ]

Application\Entity\TownEntity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: slug
            message: 'This slug is already in use'
            groups: [ newAndEdit ]
    properties:
        townResources:
            - Valid: ~

Application\Entity\TownResourceEntity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [ town, resource ]
            message: 'This town already has this resource'
            groups: [ newAndEdit ]
